### ISSUE TITLE
Add offset (pagination) to see more results

### ISSUE THREAD

**Issue by elky** [iw4p/Ton-Fragment#3]
Is it possible to add `offset` attirbute to get more results? I would like to fetch Numbers trading history to create a chart. Thanks for the lib!

**Comment by iw4p** [comment]
Hi! You're welcome. May I know for which page do you mean? If it's possible for you to go to the next page on the browser, It can be implemented by me. Just give me more specific details and I'll check it.

**Comment by elky** [comment]
To be honest I don't know is there any option to paginate the results in current Fragment API implementation. Just though you know, lol. They have https://fragment.com/js/auction.js script that possibly has some hidden things.
